---

  - name: Web Server
    hosts: web
    remote_user: ec2-user
    become: yes

    roles:
      - web

  - name: Web Server
    hosts: script
    remote_user: ec2-user
    become: yes

    roles:
      - script
