---
# tasks file for web

- name: Install the latest version of Apache
  yum:
    name: "{{ web_pkg }}"
    state: latest

- name: Copy file with owner and permissions
  #ansible.builtin.copy:
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: "{{ web_pkg }}"
