pipeline {
    agent any
    stages {
        stage('Packer Build') {
            steps {
		sh '''
                cd packer-demo
                pwd
   		env 
                packer build packer_test.json
  		'''
            }
        }

    }
}
