pipeline {
    agent any
/*
    parameters {
        choice(name: 'CHOICE', choices: ['AWS', 'AZ', 'GCP'], description: 'Pick Cloud Provider')
        string(name: 'ami_id', defaultValue: '', description: 'pass AMI ID')
        string(name: 'count', defaultValue: '', description: 'Instance Count')
        booleanParam(name: 'Destroy', defaultValue: '', description: 'Terraform Destroy')
        booleanParam(name: 'Apply', defaultValue: '', description: 'Terraform Apply')
    }
*/
/* Pradeep DevOps*/
    stages {
        stage('Packer Build') {
            steps {
		sh '''
                cd packer-demo
                pwd
                packer build packer_test.json
  		'''
            }
        }

    }
}
