  variable cidr_id{}
  variable azs_id{}
  variable private_subnets_id{}
  variable public_subnets_id{}
  variable igw_id{}
  variable ngw_id{}
  variable route_id{}
  variable count_id{}  
  variable security_groups_id{}
  variable bucket_id{}
  variable ami_id{}
  variable inst_type
  variable sub_id{}
  variable count_id{}
  variable vpc_id{}
  variable tag{}
